export const THEME_TOKENS = {
  dark: {
    pageGradient: 'from-[#050b29] via-[#0a1f5c] to-[#0b74ff]',
    blobOne: 'bg-[#4cc9ff]',
    blobTwo: 'bg-[#0a3ead]',
    primaryText: 'text-white',
    secondaryText: 'text-white/80',
    mutedText: 'text-white/60',
    accentText: 'text-[#7fd3ff]',
    badgeText: 'text-white/80',
    badgeBorder: 'border-white/20',
    cardBg: 'bg-white/5',
    cardBorder: 'border-white/15',
    statCardBg: 'bg-white/5',
    statBorder: 'border-white/15',
    statMuted: 'text-white/75',
    statValue: 'text-white',
    inputBorder: 'border-white/15',
    inputBg: 'bg-white/10',
    inputText: 'text-white',
    placeholder: 'placeholder:text-white/60',
    focusBorder: 'focus:border-[#67d0ff]',
    focusRing: 'focus:ring-[#67d0ff]/60',
    ctaGradient: 'from-[#1f7bff] to-[#65e0ff]',
    infoText: 'text-white/70',
    panelBg: 'bg-black/20',
    panelBorder: 'border-white/10',
    userBubble: 'bg-gradient-to-r from-[#1d6dff] to-[#58d5ff] text-white',
    assistantBubble: 'bg-white/10 text-white/90 border border-white/10',
    checklistDot: 'bg-[#59d3ff]',
    codeBg: 'bg-black/30',
    codeBorder: 'border-white/15',
    ghostButtonBg: 'bg-white/10',
    ghostButtonBorder: 'border-white/25',
    ghostButtonHover: 'hover:bg-white/20',
    ghostButtonText: 'text-white',
    pillSolidBg: 'bg-white/20',
    pillSolidText: 'text-white',
    pillSolidBorder: 'border-white/30',
    pillOutlineText: 'text-[#7fd3ff]',
    pillOutlineBorder: 'border-[#7fd3ff]/60',
    pillOutlineHover: 'hover:bg-[#7fd3ff]/10',
    button: 'bg-gradient-to-r from-[#1f7bff] to-[#65e0ff] text-white',
    toggleBg: 'bg-white/10',
    toggleText: 'text-white',
    emptyBorder: 'border-white/20',
    emptyText: 'text-white/70',
    surfaceBg: 'bg-white/5',
    surfaceBorder: 'border-white/15',
  },
  light: {
    pageGradient: 'from-[#add8e6] via-[#e2ecff] to-[#c7dbff]',
    blobOne: 'bg-[#a6c8ff]',
    blobTwo: 'bg-[#d4e2ff]',
    primaryText: 'text-slate-900',
    secondaryText: 'text-slate-600',
    mutedText: 'text-slate-500',
    accentText: 'text-[#2157c8]',
    badgeText: 'text-slate-600',
    badgeBorder: 'border-slate-400',
    cardBg: 'bg-white/80',
    cardBorder: 'border-slate-400',
    statCardBg: 'bg-white/90',
    statBorder: 'border-slate-400',
    statMuted: 'text-slate-500',
    statValue: 'text-slate-900',
    inputBorder: 'border-slate-400',
    inputBg: 'bg-white',
    inputText: 'text-slate-900',
    placeholder: 'placeholder:text-slate-400',
    focusBorder: 'focus:border-[#2563eb]',
    focusRing: 'focus:ring-[#2563eb]/30',
    ctaGradient: 'from-[#050b29] to-[#0b74ff]',
    infoText: 'text-slate-500',
    panelBg: 'bg-white/80',
    panelBorder: 'border-slate-400',
    userBubble: 'bg-gradient-to-r from-[#407bff] to-[#6fb9ff] text-white',
    assistantBubble: 'bg-white text-slate-800 border border-slate-400',
    checklistDot: 'bg-[#3b82f6]',
    codeBg: 'bg-slate-900/5',
    codeBorder: 'border-slate-400',
    ghostButtonBg: 'bg-white',
    ghostButtonBorder: 'border-slate-400',
    ghostButtonHover: 'hover:bg-slate-50',
    ghostButtonText: 'text-slate-700',
    pillSolidBg: 'bg-slate-900',
    pillSolidText: 'text-white',
    pillSolidBorder: 'border-slate-900',
    pillOutlineText: 'text-[#2157c8]',
    pillOutlineBorder: 'border-[#2157c8]',
    pillOutlineHover: 'hover:bg-[#2157c8]/10',
    toggleBg: 'bg-white',
    toggleText: 'text-slate-700',
    emptyBorder: 'border-slate-400',
    emptyText: 'text-slate-500',
    surfaceBg: 'bg-white/90',
    surfaceBorder: 'border-slate-400',
  },
}
